### ISSUE TITLE
Pluggable mechanizm for database adapters

### ISSUE THREAD

**Issue by repeatedly** [fluent/fluent-plugin-sql#10]
Now, fluent-plugin-sql requires `libmysqlclient-dev` for mysql2 and `libpq-dev` for pg gems on Ubuntu.
It's a pain because users want to use one database, but need more packages to install fluent-plugin-sql.
We should extract adapters from fluent-plugin-sql core and provide pluggable mechanizm like fluent-plugin-sql-adapter-mysql or similar.

**Comment by cmc476** [comment]
any plans to do this?  or make build option (with-mysql, with-pg)

**Comment by repeatedly** [comment]
Maybe `with-mysql` like option is hard because gemfile is fixed.
Ok, I will try to implement this in the next week.

**Comment by repeatedly** [comment]
I removed from mysql2 and pg gem since v0.4.0.
The user should install adapter gem manually.

https://github.com/fluent/fluent-plugin-sql#installation
