### ISSUE TITLE
How to encrypt & decrypt the password in fluentd configuration

### ISSUE THREAD

**Issue by harsh288** [fluent/fluent-plugin-sql#118]
How to encrypt the password, because of security reasons we can't keep in a text file

host rdb_host
  database rdb_database
  adapter mysql2_or_postgresql_or_etc
  username myusername
  password mypassword

This has become a huge security loophole, can someone help, this is really critical.

Note: We cannot keep the password in plain text in an environment variable.

**Comment by ashie** [comment]
Duplicate of #106
