### ISSUE TITLE
Cannot Install on Ubuntu 14.04 with td-agent-gem

### ISSUE THREAD

**Issue by jriggins** [fluent/fluent-plugin-sql#12]
I'm trying to issue on my server:

sudo /usr/sbin/td-agent-gem install fluent-plugin-sql --no-ri --no-rdoc -v '0.3.0'

However, I'm experiencing issues similar to this stackoverflow:

http://stackoverflow.com/questions/15186924/installing-gem-pg-for-postgresql-openssl-libraries

Looks like their solution was to reinstall ruby to reference to proper ssl lib.  Is there anything that you think can be done here (perhaps in the td-agent ubuntu package)?  I imagine worst case I can use the fluentd gem and my own ruby instead.

Thanks,
 Jesse

**Comment by repeatedly** [comment]
td-agent 2 includes postgresql temporary.
This issues is resolved.
