### ISSUE TITLE
Unable to fetch data from postgresql view: NilClass

### ISSUE THREAD

**Issue by yugunji** [fluent/fluent-plugin-sql#13]
Hi, I'm trying to fetch data from a view (not table) on postgresql and seeing the error as followed:

```
  2015-01-22 14:11:23 +0900 [error]: unexpected error error="can't dup NilClass" error_class=TypeError
  2015-01-22 14:11:23 +0900 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-sql-0.3.0/lib/fluent/plugin/in_sql.rb:123:in `dup'
  2015-01-22 14:11:23 +0900 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-sql-0.3.0/lib/fluent/plugin/in_sql.rb:123:in `emit_next_records'
  2015-01-22 14:11:23 +0900 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-sql-0.3.0/lib/fluent/plugin/in_sql.rb:227:in `block in thread_main'
  2015-01-22 14:11:23 +0900 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-sql-0.3.0/lib/fluent/plugin/in_sql.rb:224:in `each'
  2015-01-22 14:11:23 +0900 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-sql-0.3.0/lib/fluent/plugin/in_sql.rb:224:in `thread_main'
```

Is it possible to fetch data from a view in first place?

Regards,

**Comment by repeatedly** [comment]
Does specifing table instead of view work correctly?

**Comment by yugunji** [comment]
Yes, it does.

As looking into code, it seems there might be something wrong when fetched record is serialised.
```
      def emit_next_records(last_record, limit)
        relation = @model
        if last_record && last_update_value = last_record[@update_column]
          relation = relation.where("#{@update_column} > ?", last_update_value)
        end
        relation = relation.order("#{@update_column} ASC").limit(limit)

        now = Engine.now
        entry_name = @model.table_name.singularize

        me = MultiEventStream.new
        relation.each do |obj|
          record = obj.serializable_hash rescue nil
```
The "record" returns nil in here.

Any thoughts?

Thanks

**Comment by repeatedly** [comment]
Ah, I first know this behaviour.
I will check another way to avoid this problem.

**Comment by yugunji** [comment]
thank you so much!

**Comment by repeatedly** [comment]
I want to reproduce the problem on my environment.
Could you paste the your table and view setting?

**Comment by yugunji** [comment]
I'm so sorry but the setting for both table and view is including the confidential information so it's hard to give it to you.

**Comment by repeatedly** [comment]
Simplied case is enough for test.
Column name to 1 character, removing imporant columns, etc...
The important thing is sharing unexpected behaviour between I and you :)

**Comment by repeatedly** [comment]
If hard to show simplified case, no problem.
I will setup test case later.

**Comment by repeatedly** [comment]
ActiveRecord seems to require primary key in object construction but your view doesn't have a primary key.
Can PostgreSQL's view specify a primary key?

**Comment by yugunji** [comment]
Sorry for being late to response, I've been missing your comment.

Hmm, it seems PostgreSQL doesn't support primary key on view...

**Comment by yugunji** [comment]
this might be a help?
haven't run enough test though due to the file disclosure problem on my mac > <

please ignore if it doesn't help anything.

```ruby
--- a/lib/fluent/plugin/in_sql.rb
+++ b/lib/fluent/plugin/in_sql.rb
@@ -46,6 +46,7 @@ module Fluent
       config_param :tag, :string, :default => nil
       config_param :update_column, :string, :default => nil
       config_param :time_column, :string, :default => nil
+      config_param :pkey, :string, :default => nil
 
       def configure(conf)
         super
@@ -59,6 +60,9 @@ module Fluent
         @model = Class.new(base_model) do
           self.table_name = table_name
           self.inheritance_column = '_never_use_'
+          if @pkey
+            self.primary_key = @pkey
+          end
           #self.include_root_in_json = false
 
           def read_attribute_for_serialization(n)
```

**Comment by yugunji** [comment]
Confirmed the above code seems to work fine on my environment.

**Comment by repeatedly** [comment]
Thanks. I will apply above patch and release new verison. Please wait.

**Comment by yugunji** [comment]
:-)

**Comment by repeatedly** [comment]
Released
