### ISSUE TITLE
How to debug?

### ISSUE THREAD

**Issue by cmc476** [fluent/fluent-plugin-sql#15]
There are precious few debug points in the plugin - if there is a process using fluent-debug let me know and I'm happy to contribute to readme.

**Comment by repeatedly** [comment]
I don't understand what you say correctly.
Do you want to know fluent-debug usage or debugging know-how of sql plugin?

**Comment by cmc476** [comment]
debugging know-how of sql-plugin, the reference to fluent-debug was me trying to find a method.  Essentially, fluentd is starting successfully, sql plugin is loaded properly, and some log (using tail input) entries find their way to sql, but not all of them, I'm hoping there is a method to see the sql inserts in real time to determine the problem (no errors in fluent log when specifying -vv command option)

**Comment by edsiper** [comment]
which output plugin are you using or are you building a SQL output plugin ?, I understand you are inserting some SQL records but we need more details.

**Comment by cmc476** [comment]
mysql2 with fluent-plugin-sql output plugin.  input is type tail.

<source>
   type tail
   path mylogfile
   pos_file mylogfile.pos
   tag myapp 
   format json
</source>
<match myapp.**>
  type sql
  host localhost
  port 3306
  database mydb
  username root
  adapter mysql2
  remove_tag_prefix myapp.**
  <table>
     table mytable
     column_mapping 'field1:field1,field2:field2,field3:field3'
  </table>
</match>

**Comment by cmc476** [comment]
I isolated my issue, but would still be good to have debugging for any issues in the future.

**Comment by repeatedly** [comment]
Okay. Yeah, we are now considering to add performance profiling and debug features.
