### ISSUE TITLE
warn parameter 'pattern' in <table>

### ISSUE THREAD

**Issue by Darrelk** [fluent/fluent-plugin-sql#16]
Using table with pattern does not work. gives the following warnings:

<code>
2015-05-29 07:22:50 +0000 [warn]: Detect duplicate default table definition

2015-05-29 07:22:50 +0000 [warn]: parameter 'pattern' in \<table\>
  pattern my.tag
  table Table1
  column_mapping filed:field
\</table\> is not used.
</code>

How to I get to use multiple tables with different patterns?

It always uses the last specified table. So all my data is written to the last table, and never to what it should match.

here is my match config:
<code>
```xml
<match sql.table.**>
	type sql
	host 127.0.0.1
	port 3306
	database database1
	adapter mysql2
	username root
	password root
	remove_tag_prefix sql.table

	<table>
		pattern tablename
		table tablename
		column_mapping 'id:id,field1:field1'
	</table>			
	
	<table>
		pattern tablename2
		table tablename2
		column_mapping 'id:id,field1:field1,field2:field2'
	</table>				
		
</match>
```
</code>

**Comment by repeatedly** [comment]
It seems document is wrong.
How about using following configuration?

```aconf
<match sql.table.**>
    type sql
    host 127.0.0.1
    port 3306
    database database1
    adapter mysql2
    username root
    password root
    remove_tag_prefix sql.table

    <table tablename>
        table tablename
        column_mapping 'id:id,field1:field1'
    </table>            

    <table>
        table tablename2
        column_mapping 'id:id,field1:field1,field2:field2'
    </table>                
</match>
```

pattern is specified in `<table>` element like `match`

**Comment by Darrelk** [comment]
Thanks for the quick replay.

it works with full tag when "remove_tag_prefix" is not specified.

Can you please update the usage docs with <table pattern>

**Comment by repeatedly** [comment]
Updated!

**Comment by Darrelk** [comment]
Thank you very much.
