### ISSUE TITLE
Missing milliseconds in dates/datetime/timestamps

### ISSUE THREAD

**Issue by static-max** [fluent/fluent-plugin-sql#24]
Milliseconds are dropped, even though PostgreSQL und MySQL support it.
My dates will look like this: "2014-04-04 14:54:07 UTC", the milliseconds are gone :(.

See http://stackoverflow.com/questions/14107354/millisecond-resolution-of-datetime-in-ruby

**Comment by repeatedly** [comment]
This is limitation of current stable fluentd version.
Please try v0.14.0.pre1.

**Comment by phongtattuan** [comment]
@repeatedly @static-max 
I think it is an issue of convert `Time` object to string ([line 96](https://github.com/fluent/fluent-plugin-sql/blob/master/lib/fluent/plugin/in_sql.rb#L96))

Example:
```ruby
def read_attribute_for_serialization(n)
  v = send(n)
  if v.respond_to?(:to_msgpack)
    v
  elsif v.is_a? Time
    v.strftime('%Y-%m-%d %H:%M:%S.%6N%z') # for convinient, we can add `time_format` config
  else
    v.to_s
  end
end
```

I can create a PR for this issue.

**Comment by repeatedly** [comment]
Release v0.6.0 including @phongtattuan's patch.
