### ISSUE TITLE
/etc/init.d/td-agent start   

### ISSUE THREAD

**Issue by liusunpan** [fluent/fluent-plugin-sql#36]
Starting td-agent: 2016-04-28 15:01:00 +0800 [error]: fluent/supervisor.rb:359:rescue in main_process: config error file="/etc/td-agent/td-agent.conf" error="Unknown output plugin 'sql'. Run 'gem search -rd fluent-plugin' to find plugins"

Successfully installed fluent-plugin-sql-0.5.1
Parsing documentation for fluent-plugin-sql-0.5.1
Done installing documentation for fluent-plugin-sql after 0 seconds
1 gem installed

**Comment by repeatedly** [comment]
Cold you check http://docs.fluentd.org/articles/plugin-management#fluent-gem ?

**Comment by liusunpan** [comment]
/usr/sbin/td-agent-gem install  fluent-plugin-sql       
After the successful launch of the installation, thank you

**Comment by repeatedly** [comment]
Good to hear. Closed
