### ISSUE TITLE
When I have field named "changed" in my db schema I get an error

### ISSUE THREAD

**Issue by permyakovsv** [fluent/fluent-plugin-sql#42]
[error]: unexpected error error="changed is defined by Active Record. Check to make sure that you don't have an attribute or method with the same name." error_class=ActiveRecord::DangerousAttributeError

**Comment by repeatedly** [comment]
This is sql plugin limitation.
You seems to have a column named "changed" and it conflicts ActiveRecord semantics.
If you can't rename such column, using mysql or pg plugin is better.
