### ISSUE TITLE
error Failed to build gem native extension when trying to install mysql2

### ISSUE THREAD

**Issue by boynet** [fluent/fluent-plugin-sql#51]
on fresh ubuntu 16

just running this commands:
```
curl -L https://toolbelt.treasuredata.com/sh/install-ubuntu-xenial-td-agent2.sh | sh
/etc/init.d/td-agent restart
/etc/init.d/td-agent status
 /usr/sbin/td-agent-gem install fluent-plugin-sql --no-document
 /usr/sbin/td-agent-gem install mysql2 --no-document
```

getting this error:

> Building native extensions.  This could take a while...
> ERROR:  Error installing mysql2:
>         ERROR: Failed to build gem native extension.
> 
>     /opt/td-agent/embedded/bin/ruby -r ./siteconf20170720-26354-32lupl.rb extconf.rb
> checking for rb_absint_size()... *** extconf.rb failed ***
> Could not create Makefile due to some reason, probably lack of necessary
> libraries and/or headers.  Check the mkmf.log file for more details.  You may
> need configuration options.
> 
> Provided configuration options:
>         --with-opt-dir
>         --with-opt-include
>         --without-opt-include=${opt-dir}/include
>         --with-opt-lib
>         --without-opt-lib=${opt-dir}/lib
>         --with-make-prog
>         --without-make-prog
>         --srcdir=.
>         --curdir
>         --ruby=/opt/td-agent/embedded/bin/ruby
> /opt/td-agent/embedded/lib/ruby/2.1.0/mkmf.rb:467:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
> You have to install development tools first.
>         from /opt/td-agent/embedded/lib/ruby/2.1.0/mkmf.rb:552:in `try_link0'
>         from /opt/td-agent/embedded/lib/ruby/2.1.0/mkmf.rb:567:in `try_link'
>         from /opt/td-agent/embedded/lib/ruby/2.1.0/mkmf.rb:747:in `try_func'
>         from /opt/td-agent/embedded/lib/ruby/2.1.0/mkmf.rb:1032:in `block in have_func'
>         from /opt/td-agent/embedded/lib/ruby/2.1.0/mkmf.rb:923:in `block in checking_for'
>         from /opt/td-agent/embedded/lib/ruby/2.1.0/mkmf.rb:351:in `block (2 levels) in postpone'
>         from /opt/td-agent/embedded/lib/ruby/2.1.0/mkmf.rb:321:in `open'
>         from /opt/td-agent/embedded/lib/ruby/2.1.0/mkmf.rb:351:in `block in postpone'
>         from /opt/td-agent/embedded/lib/ruby/2.1.0/mkmf.rb:321:in `open'
>         from /opt/td-agent/embedded/lib/ruby/2.1.0/mkmf.rb:347:in `postpone'
>         from /opt/td-agent/embedded/lib/ruby/2.1.0/mkmf.rb:922:in `checking_for'
>         from /opt/td-agent/embedded/lib/ruby/2.1.0/mkmf.rb:1031:in `have_func'
>         from extconf.rb:26:in `<main>'
> 
> extconf failed, exit code 1
> 
> Gem files will remain installed in /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/mysql2-0.4.8 for inspection.
> Results logged to /opt/td-agent/embedded/lib/ruby/gems/2.1.0/extensions/x86_64-linux/2.1.0/mysql2-0.4.8/gem_make.out

I tried running  `sudo apt-get install libmysqlclient-dev` and then tried again to install mysql2 but no luck same error

**Comment by repeatedly** [comment]
Did you install development tools?

**Comment by boynet** [comment]
yes I tried by running `sudo apt-get install libmysqlclient-dev` but on second look I guess it's not the right development tools?

**Comment by repeatedly** [comment]
> libmysqlclient-dev

This is mysql client headers, not development tools.
development tools means ruby-dev, make, autoconf and etc.

**Comment by boynet** [comment]
Thanks my mistake..
I don't know which of this packages help me but this installs solved it for me:
` sudo apt-get install build-essential bison openssl libreadline6 libreadline6-dev curl git-core zlib1g zlib1g-dev libssl-dev libyaml-dev libxml2-dev autoconf libc6-dev ncurses-dev automake libtool`
