### ISSUE TITLE
(output plugin) Store fluent tag into db table column.

### ISSUE THREAD

**Issue by panta** [fluent/fluent-plugin-sql#52]
Is there a way to store the fluent tag into a table column?
In the examples different tags are directed to different tables, but in my case I have many subsystems (hence different tags), all logging to the same table, so it is necessary to be able to know the tag of each logged entry.
If it is not already implemented, I'd also appreciate any pointer on how to add this myself.

Thanks in advance.

**Comment by repeatedly** [comment]
Use record_transfomer or similar plugin to add tag to record: https://docs.fluentd.org/v1.0/articles/filter_record_transformer

**Comment by panta** [comment]
Wonderful, thank you!
