### ISSUE TITLE
Credentials from env

### ISSUE THREAD

**Issue by vwbusguy** [fluent/fluent-plugin-sql#61]
We are planning on dockerizing our SQL agent and would like to pass the database config credentials via env so that it can be reproducable/re-usable without having to hard-code the credentials into a flat file somewhere.  
For example, the [record_transformer](https://docs.fluentd.org/v0.12/articles/filter_record_transformer) filter plugin allows for Ruby expressions.  Perhaps something similar could be implemented for this plugin, such as:

```
host ${ENV["DBHOST"]}
database ${ENV["DBNAME"]}
...
```

**Comment by repeatedly** [comment]
Use configuration feature: https://docs.fluentd.org/v1.0/articles/config-file#embedded-ruby-code
