### ISSUE TITLE
Missing milliseconds in dates/datetime/timestamps - oracle

### ISSUE THREAD

**Issue by nkravi** [fluent/fluent-plugin-sql#63]
timestamp is trimmed for oracle 12.x version. 
#24 fix doesn't work for oracle.

**Comment by eherot** [comment]
This does not appear to be just an Oracle issue. Milliseconds are also being dropped from MS SQL timestamps. I can confirm that they are being parsed properly, but the fact that parsed timestamps are being converted to integers before being fed into FluentD appears to be part of the problem.
