### ISSUE TITLE
td-agent Service fails to start after installing fluent-plugin-sql

### ISSUE THREAD

**Issue by roligupt** [fluent/fluent-plugin-sql#96]
I installed td-agent_3.8.0-0_amd64.deb on my ubuntu 18.04 server. it all works fine until i install the fluent-plugin-sql. The service fails to start. 

Not sure what is the issue but I did try to follow the workaround steps that someone tried to fix their issue on issue "https://github.com/fluent/fluent-plugin-sql/issues/87"  The workaround mentioned in this issue didnt fix my issue and the service still fails to start.

**Comment by roligupt** [comment]
My issue was with the umask, root umask was set to 027 and plugins were being installed with not enough permissions. I had already uninstalled all the plugins for finding the issue. I reinstalled them after changing the umask 022 (002 will work as well).

**Comment by kenhys** [comment]
On Ubuntu 18.04 sever (18.04.5 fresh installed), umask is set to 0022(root) or 0002(user).
So it seems that this is your server specific issue.
